### ISSUE TITLE
Create GitHub Actions workflow for running tests automatically

### ISSUE THREAD

**Issue by hellovietduc** [mindxhub/dna-go#14]

**Comment by trungducc** [comment]
@vietduc01100001 Could you explain why this issue is closed? I really want to fix this issue before merging PRs.

**Comment by hellovietduc** [comment]
> @vietduc01100001 Could you explain why this issue is closed? I really want to fix this issue before merging PRs.

Before I thought the workflow file would run on forks as well, but seems like it doesn't. So I moved the file to each branch on my fork and the test did run. However the test results didn't show up in the PRs, only visible on my fork. So I guess merging a PR will activate that?
